name: Enterprise Terraform CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1

jobs:

# ================= PLAN (PR VALIDATION) =================
  plan:
    name: Terraform Plan (PR)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (DEV)
        run: terraform init
        working-directory: enviroments/dev

      - name: Terraform Plan (DEV)
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: enviroments/dev


# ================= DEV DEPLOY =================
  dev:
    name: Deploy to DEV
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: enviroments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: enviroments/dev


# ================= STAGE DEPLOY =================
  stage:
    name: Deploy to STAGE
    needs: dev
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: enviroments/stage

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: enviroments/stage


# ================= PROD DEPLOY =================
  prod:
    name: Deploy to PROD
    needs: stage
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: enviroments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: enviroments/prod
